services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vulntrack
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-change_me}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  server:
    build: ./server
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    
    environment:
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET:-dev_secret}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-vulntrack}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:5173,http://localhost:8080}
      - HOME=/tmp
      - NPM_CONFIG_CACHE=/tmp/.npm
    restart: unless-stopped
    command: sh -c "npm install && node index.js"
    depends_on:
      - postgres
    # run as root in dev to avoid volume permission issues during npm install

  client:
    build: ./client
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "5173:8080"
    volumes:
      - ./client:/app
    environment:
      - VITE_API_URL=http://localhost:3001
      - HOME=/tmp
      - NPM_CONFIG_CACHE=/tmp/.npm
    restart: unless-stopped
    command: sh -c "npm install && npm run dev"
    # run as root in dev to avoid volume permission issues during npm install


volumes:
  pg_data:
  pgadmin_data:
